### ISSUE TITLE
Tag text overflow for large content

### ISSUE THREAD

**Issue by muhd-ameen** [raLaaaa/simple_tags#1]
![flutter_01](https://user-images.githubusercontent.com/59697692/229721343-d42d9bcf-7e34-4b1c-a5eb-f81ca941d15e.png)

**Comment by raLaaaa** [comment]
Hey, I'll dig into this. Unfortunately I'm quite busy right now - I'll get back to you asap.

**Comment by muhd-ameen** [comment]
That’s awesome 🏎️🏎️

**Comment by raLaaaa** [comment]
@muhd-ameen - I released a quick fix for this with version `0.0.5` - this should atleast fix the overflow error.

See the updated readme for an example. Please let me know whether this helps you and upgrading to `0.0.5` works for you - I did not do it in a while and hope I did the correct steps.

----

Update: please use `0.0.6` :)

**Comment by raLaaaa** [comment]
@muhd-ameen did the update fix your issue? In that case I would close the issue.

**Comment by muhd-ameen** [comment]
Of course its works, more power to you 😃
