### ISSUE TITLE
Delete tag

### ISSUE THREAD

**Issue by EliaTolin** [raLaaaa/simple_tags#2]
Is possible add the function "onDelete"? 
Otherwise change Icon to IconButton.

**Comment by raLaaaa** [comment]
Hey, I'm not quite sure if I understand this correctly.

Do you need a general `onDelete` hook when a tag is removed from the underlying tag list?
Right now there is only a `onTagPress` hook which fires if you press the icon no matter whether you clock the `icon` on the element or not. 

If I understand you correctly you need two functionalites for each element:

- if you click the element
- if you click on the tagIcon of the element

is that correct?

**Comment by raLaaaa** [comment]
Closing this for too unspecific.
